<?php

namespace App\Service\game;

use Symfony\Contracts\HttpClient\HttpClientInterface;
use Psr\Log\LoggerInterface;

class HuggingFaceService
{
    private const API_URL = 'https://router.huggingface.co/novita/v3/openai/chat/completions';
    
    public function __construct(
        private HttpClientInterface $httpClient,
        private LoggerInterface $logger,
        private string $huggingFaceApiKey
    ) {
    }

    /**
     * Generate trivia questions using Hugging Face API
     * 
     * @param string $topic The topic for questions
     * @param int $count Number of questions to generate (default: 5)
     * @param string $difficulty Difficulty level (EASY, MEDIUM, HARD)
     * @return array Array of questions with choices and correct answers
     * @throws \Exception If API call fails
     */
    public function generateTriviaQuestions(string $topic, int $count = 5, string $difficulty = 'MEDIUM'): array
    {
        if (empty($this->huggingFaceApiKey)) {
            throw new \Exception('Hugging Face API key is not configured. Please set HUGGING_FACE_API_KEY in .env file.');
        }

        $prompt = $this->buildPrompt($topic, $count, $difficulty);

        try {
            $response = $this->httpClient->request('POST', self::API_URL, [
                'headers' => [
                    'Authorization' => 'Bearer ' . $this->huggingFaceApiKey,
                    'Content-Type' => 'application/json',
                ],
                'json' => [
                    'model' => 'qwen/qwen2.5-7b-instruct',
                    'messages' => [
                        ['role' => 'user', 'content' => $prompt]
                    ],
                    'max_tokens' => 2000,
                    'temperature' => 0.7,
                ],
                'timeout' => 60,
                'max_duration' => 60,
            ]);

            $statusCode = $response->getStatusCode();
            
            if ($statusCode !== 200) {
                $errorContent = $response->getContent(false);
                $this->logger->error('Hugging Face API error', [
                    'status_code' => $statusCode,
                    'response' => $errorContent
                ]);
                
                // Try to parse error message
                $errorData = json_decode($errorContent, true);
                $errorMsg = $errorData['error'] ?? 'API returned status: ' . $statusCode;
                
                if ($statusCode === 401) {
                    throw new \Exception('Hugging Face API key is invalid or expired. Please update your API key in .env file.');
                }
                
                throw new \Exception('Failed to generate questions. ' . $errorMsg);
            }

            $data = $response->toArray();
            
            // Extract generated text
            $generatedText = $data['choices'][0]['message']['content'] ?? '';
            
            if (empty($generatedText)) {
                throw new \Exception('No content generated by AI');
            }

            // Parse the generated text to extract questions
            $questions = $this->parseGeneratedQuestions($generatedText, $count);

            if (empty($questions)) {
                throw new \Exception('Failed to parse generated questions. Please try again.');
            }

            return $questions;

        } catch (\Exception $e) {
            $this->logger->error('Hugging Face API call failed', [
                'error' => $e->getMessage(),
                'topic' => $topic
            ]);
            throw $e;
        }
    }

    /**
     * Build the prompt for question generation
     */
    private function buildPrompt(string $topic, int $count, string $difficulty): string
    {
        $difficultyInstructions = match($difficulty) {
            'EASY' => 'Make the questions suitable for beginners. Use simple language and straightforward concepts.',
            'HARD' => 'Make the questions challenging and detailed. Include advanced concepts and require deeper knowledge.',
            default => 'Make the questions moderately challenging with clear but not overly simple concepts.',
        };

        return <<<PROMPT
Generate exactly {$count} multiple choice trivia questions about "{$topic}".

Difficulty Level: {$difficulty}
{$difficultyInstructions}

For each question, provide:
1. The question text
2. Four answer choices (A, B, C, D)
3. The correct answer (indicate which letter is correct)

Format each question exactly like this:

Q1: [Question text here]
A) [First choice]
B) [Second choice]
C) [Third choice]
D) [Fourth choice]
Correct: [A/B/C/D]

Make the questions educational, clear, and appropriate for students. Ensure one answer is clearly correct and the others are plausible but incorrect.

Begin generating the questions now:
PROMPT;
    }

    /**
     * Parse generated text into structured question array
     */
    private function parseGeneratedQuestions(string $text, int $expectedCount): array
    {
        $questions = [];
        
        // Split by question markers (Q1:, Q2:, etc.)
        $pattern = '/Q\d+:\s*(.+?)(?=Q\d+:|$)/s';
        preg_match_all($pattern, $text, $matches);

        foreach ($matches[1] as $questionBlock) {
            $question = $this->parseQuestionBlock($questionBlock);
            if ($question) {
                $questions[] = $question;
            }
        }

        // If parsing failed, try alternative format
        if (empty($questions)) {
            $questions = $this->parseAlternativeFormat($text);
        }

        // Limit to expected count
        return array_slice($questions, 0, $expectedCount);
    }

    /**
     * Parse a single question block
     */
    private function parseQuestionBlock(string $block): ?array
    {
        $lines = array_filter(array_map('trim', explode("\n", $block)));
        
        if (empty($lines)) {
            return null;
        }

        $questionText = '';
        $choices = [];
        $correctAnswer = null;

        foreach ($lines as $line) {
            // Extract question text (first non-choice line)
            if (empty($questionText) && !preg_match('/^[A-D]\)/', $line) && !preg_match('/^Correct:/i', $line)) {
                $questionText = trim($line);
                continue;
            }

            // Extract choices (A), B), C), D))
            if (preg_match('/^([A-D])\)\s*(.+)$/i', $line, $match)) {
                $choices[] = trim($match[2]);
                continue;
            }

            // Extract correct answer
            if (preg_match('/^Correct:\s*([A-D])/i', $line, $match)) {
                $letter = strtoupper($match[1]);
                $correctAnswer = ord($letter) - ord('A'); // Convert A=0, B=1, C=2, D=3
                continue;
            }
        }

        // Validate we have all required parts
        if (empty($questionText) || count($choices) !== 4 || $correctAnswer === null) {
            return null;
        }

        return [
            'question' => $questionText,
            'choices' => $choices,
            'correct' => $correctAnswer
        ];
    }

    /**
     * Try alternative parsing format
     */
    private function parseAlternativeFormat(string $text): array
    {
        $questions = [];
        
        // Try to find JSON format if AI returned it
        if (preg_match('/\[.*\]/s', $text, $jsonMatch)) {
            try {
                $decoded = json_decode($jsonMatch[0], true);
                if (is_array($decoded)) {
                    foreach ($decoded as $item) {
                        if (isset($item['question'], $item['choices'], $item['correct'])) {
                            $questions[] = [
                                'question' => $item['question'],
                                'choices' => array_values($item['choices']),
                                'correct' => (int)$item['correct']
                            ];
                        }
                    }
                }
            } catch (\Exception $e) {
                // JSON parsing failed, continue with other methods
            }
        }

        return $questions;
    }

    /**
     * Test API connection
     */
    public function testConnection(): bool
    {
        if (empty($this->huggingFaceApiKey)) {
            $this->logger->error('Hugging Face API key is empty');
            return false;
        }
        try {
            $response = $this->httpClient->request('POST', 'https://router.huggingface.co/novita/v3/openai/chat/completions', [
                'headers' => [
                    'Authorization' => 'Bearer ' . $this->huggingFaceApiKey,
                    'Content-Type' => 'application/json',
                ],
                'json' => [
                    'model' => 'qwen/qwen2.5-7b-instruct',
                    'messages' => [['role' => 'user', 'content' => 'Say hello']],
                    'max_tokens' => 10,
                ],
                'timeout' => 60,
                'max_duration' => 60,
                'verify_peer' => false,
                'verify_host' => false,
            ]);
            
            $statusCode = $response->getStatusCode();
            $this->logger->info('HF test connection status: ' . $statusCode);
            return $statusCode === 200;
        } catch (\Exception $e) {
            $this->logger->error('HF test connection error: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * General chat method for AI assistants
     * 
     * @param string $userMessage The user's message
     * @param string $systemPrompt The system prompt with context
     * @return string The AI's response
     * @throws \Exception If API call fails
     */
    public function chat(string $userMessage, string $systemPrompt = ''): string
    {
        if (empty($this->huggingFaceApiKey)) {
            throw new \Exception('Hugging Face API key is not configured.');
        }

        try {
            $messages = [];
            
            // Add system prompt if provided
            if (!empty($systemPrompt)) {
                $messages[] = ['role' => 'system', 'content' => $systemPrompt];
            }
            
            // Add user message
            $messages[] = ['role' => 'user', 'content' => $userMessage];

            $response = $this->httpClient->request('POST', self::API_URL, [
                'headers' => [
                    'Authorization' => 'Bearer ' . $this->huggingFaceApiKey,
                    'Content-Type' => 'application/json',
                ],
                'json' => [
                    'model' => 'qwen/qwen2.5-7b-instruct',
                    'messages' => $messages,
                    'max_tokens' => 100,
                    'temperature' => 0.3,
                ],
                'timeout' => 60,
                'max_duration' => 60,
            ]);

            if ($response->getStatusCode() !== 200) {
                $errorContent = $response->getContent(false);
                $this->logger->error('Hugging Face chat API error', [
                    'status_code' => $response->getStatusCode(),
                    'response' => $errorContent
                ]);
                
                // Try to parse error message
                $errorData = json_decode($errorContent, true);
                $errorMsg = $errorData['error'] ?? 'API returned status: ' . $response->getStatusCode();
                
                if ($response->getStatusCode() === 401) {
                    throw new \Exception('Hugging Face API key is invalid or expired. Please update your API key.');
                }
                
                throw new \Exception('AI service error: ' . $errorMsg);
            }

            $data = $response->toArray();
            $message = $data['choices'][0]['message']['content'] ?? '';
            
            if (empty($message)) {
                throw new \Exception('No response from AI');
            }

            return trim($message);

        } catch (\Exception $e) {
            $this->logger->error('Hugging Face chat failed', [
                'error' => $e->getMessage(),
                'user_message' => $userMessage
            ]);
            throw $e;
        }
    }
}
