CREATE TABLE IF NOT EXISTS game_content (
    id INT AUTO_INCREMENT NOT NULL, 
    game_id INT NOT NULL, 
    data JSON DEFAULT NULL, 
    UNIQUE INDEX UNIQ_6B074F86E48FD905 (game_id), 
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

ALTER TABLE game_content 
ADD CONSTRAINT FK_6B074F86E48FD905 
FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE;
